---

- name: Install Python mysqldb
  apt: name=python-mysqldb state=latest

- name: Create drupal database
  mysql_db: db={{ item }} state=present
  with_items:
    - "{{ db_name_drupal }}"
    - "{{ db_name_civicrm }}"
  
- name: Create drupal user
  mysql_user: >
    name={{ db_user }}
    password={{ db_password }}
    priv={{ db_name_drupal }}.*:ALL
    priv={{ db_name_civicrm }}.*:ALL
    host=localhost
